package com.XWorkz.inheritence.Runner;

import com.XWorkz.inheritence.*;
import com.XWorkz.inheritence.Internal.Bikes;
import com.XWorkz.inheritence.Internal.Car;
import com.XWorkz.inheritence.Internal.*;
import com.XWorkz.inheritence.Internal.Vehicles;

public class MainRunner {
    public static void main(String[] args) {

        Festival festival1 =new Festival();
        festival1.ganeshaChathurthi();
        festival1.Holi();
        festival1.ugadi();
        festival1.ramzan();
        festival1.diwali();
        Festival festival = new Carnival();
        festival.ramzan();
        festival.diwali();
        festival.ugadi();
        festival.Holi();
        festival.ganeshaChathurthi();
        System.out.println("-------------------------------");
        Vehicles vehicle = new Vehicles();
        vehicle.Stop();
        vehicle.Move();
        vehicle.Sell();
        vehicle.Buy();
        vehicle.Start();
        Vehicles vehicles = new Car();
        vehicles.Buy();
        vehicles.Start();
        vehicles.Move();
        vehicles.Sell();
        vehicles.Stop();
        System.out.println("-------------------------------");
        Vehicles vehicles10 = new Vehicles();
        vehicles10.Stop();
        vehicles10.Move();
        vehicles10.Sell();
        vehicles10.Buy();
        vehicles10.Start();
        Vehicles vehicles1 = new Bikes();
        vehicles1.Stop();
        vehicles1.Sell();
        vehicles1.Start();
        vehicles1.Buy();
        vehicles1.Move();
        System.out.println("-------------------------------");
        Vehicles vehicles11 = new Vehicles();
        vehicles11.Stop();
        vehicles11.Move();
        vehicles11.Sell();
        vehicles11.Buy();
        vehicles11.Start();
        Vehicles vehicles2 = new JCB();
        vehicles2.Move();
        vehicles2.Buy();
        vehicles2.Stop();
        vehicles2.Start();
        vehicles2.Sell();
        System.out.println("-------------------------------");
        Vehicles vehicles12 = new Vehicles();
        vehicles12.Stop();
        vehicles12.Move();
        vehicles12.Sell();
        vehicles12.Buy();
        vehicles12.Start();
        Vehicles vehicles3 = new Bus();
        vehicles3.Sell();
        vehicles3.Stop();
        vehicles3.Move();
        vehicles3.Start();
        vehicles3.Buy();
        System.out.println("-------------------------------");
        Vehicles vehicles13 = new Vehicles();
        vehicles13.Stop();
        vehicles13.Move();
        vehicles13.Sell();
        vehicles13.Buy();
        vehicles13.Start();
        Vehicles vehicles4 = new Train();
        vehicles4.Buy();
        vehicles4.Move();
        vehicles4.Sell();
        vehicles4.Stop();
        vehicles4.Start();
        System.out.println("-------------------------------");
        Vehicles vehicles14 = new Vehicles();
        vehicles14.Stop();
        vehicles14.Move();
        vehicles14.Sell();
        vehicles14.Buy();
        vehicles14.Start();
        Vehicles vehicles5 = new PickUp();
        vehicles5.Start();
        vehicles5.Stop();
        vehicles5.Sell();
        vehicles5.Move();
        vehicles5.Buy();
        System.out.println("-------------------------------");
        Vehicles vehicles15 = new Vehicles();
        vehicles15.Stop();
        vehicles15.Move();
        vehicles15.Sell();
        vehicles15.Buy();
        vehicles15.Start();
        Vehicles vehicles6 = new Troctor();
        vehicles6.Buy();
        vehicles6.Move();
        vehicles6.Sell();
        vehicles6.Buy();
        vehicles6.Start();
        System.out.println("-------------------------------");
        Vehicles vehicles16 = new Vehicles();
        vehicles16.Stop();
        vehicles16.Move();
        vehicles16.Sell();
        vehicles16.Buy();
        vehicles16.Start();
        Vehicles vehicles7 = new Troctor();
        vehicles7.Buy();
        vehicles7.Start();
        vehicles7.Sell();
        vehicles7.Move();
        vehicles7.Stop();
        System.out.println("-------------------------------");
        Vehicles vehicles17 = new Vehicles();
        vehicles17.Stop();
        vehicles17.Move();
        vehicles17.Sell();
        vehicles17.Buy();
        vehicles17.Start();
        System.out.println("...................................");
        Vehicles vehicles18 = new Vehicles();
        vehicles18.Stop();
        vehicles18.Move();
        vehicles18.Sell();
        vehicles18.Buy();
        vehicles18.Start();
        Vehicles vehicles8 = new Tillar();
        vehicles8.Stop();
        vehicles8.Move();
        vehicles8.Buy();
        vehicles8.Sell();
        vehicles8.Start();
        System.out.println("<><><><><><><><><><><><>><><><>><><><><><>");
        Vehicles vehicles19 = new Vehicles();
        vehicles19.Stop();
        vehicles19.Move();
        vehicles19.Sell();
        vehicles19.Buy();
        vehicles19.Start();
        Vehicles vehicles9 = new Cycle();
        vehicles9.Start();
        vehicles9.Buy();
        vehicles9.Sell();
        vehicles9.Move();
        vehicles9.Stop();
        System.out.println("[][][][][][][][][][][][][][][][][][][][][][][][][][]");
        Apple apple = new Fruit();
        apple.type();
        apple.Size();
        apple.kg();
        apple.price();
        apple.colour();
        System.out.println("()()()()()()()()()()()()()()()()()()()()()()");
        Place place = new Place();
        place.nature();
        place.area();
        place.nearPlace();
        place.distance();
        place.location();
        Place place1 = new Thirthahalli();
        place1.area();
        place1.nearPlace();
        place1.distance();
        place1.location();
        place1.nature();
        System.out.println("{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}");
        Place place11 = new Place();
        place11.nature();
        place11.area();
        place11.nearPlace();
        place11.distance();
        place11.location();
        Place place2 = new Koppa();
        place2.nature();
        place2.nearPlace();
        place2.distance();
        place2.location();
        place2.area();
        System.out.println("======================================================");
        Place place12 = new Place();
        place12.nature();
        place12.area();
        place12.nearPlace();
        place12.distance();
        place12.location();
        Place place3 = new Shivamogga();
        place3.location();
        place3.nature();
        place3.nearPlace();
        place3.area();
        place3.distance();
        System.out.println("______________________________________________________");
        Report report = new Document();
        report.conclusion();
        report.introduction();
        report.flowChart();
        report.systemDesign();
        report.conclusion();
        System.out.println("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
        Home home = new Building();
        home.bathRoom();
        home.bedRoom();
        home.hall();
        home.dinningHall();
        home.kitchen();
        System.out.println("*************************************************************");
        Sand sand = new Soil();
        sand.area();
        sand.color();
        sand.quality();
        sand.type();
        sand.quantity();
        System.out.println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
        Rupee money = new Paisa();
        money.loanAmont();
        money.cash();
        money.intrest();
        money.UIP();
        money.payment();
        System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
        Hotel hotel = new Canteen();
        hotel.business();
        hotel.dosa();
        hotel.plate();
        hotel.business();
        hotel.supplear();
        System.out.println("####################################################################");
        Hostel hostel = new PG();
        hostel.Fees();
        hostel.Food();
        hostel.location();
        hostel.sharing();
        hostel.students();
        System.out.println("----------------------------------------");
        Bar bar = new wineShop();
        bar.barLocation();
        bar.area();
        bar.beer();
        bar.brand();
        bar.owner();
        System.out.println("------------------------------------------");
        Brand brand = new Counter();
        brand.BP();
        brand.MC();
        brand.Beer();
        brand.MC();
        brand.RS();
        System.out.println("------------------------------------------");
        Battery battery = new Torch();
        battery.batterColor();
        battery.batterCost();
        battery.charge();
        battery.Shell();
        battery.singleLight();
        System.out.println("--------------------------------------------");
        Dog cow = new animalHarsha();
        cow.cowBread();
        cow.cowColour();
        cow.cowName();
        cow.cowPrice();
        cow.cowSize();
        System.out.println("-----------------------------------------------");
        Parrot parrot = new Birds();
        parrot.parrotColor();
        parrot.gender();
        parrot.number();
        parrot.weight();
        parrot.parrotLocation();
        System.out.println("------------------------------------------------");
        Mobile mobile = new Phone();
        mobile.Mi();
        mobile.call();
        mobile.price();
        mobile.text();
        mobile.types();
        System.out.println("-------------------------------------------------");
        Place place20 = new Banglure();
        place20.distance();
        place20.area();
        place20.location();
        place20.nature();
        place.nearPlace();
        System.out.println("*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*");
        Place place4 = new Srigeri();
        place4.nearPlace();
        place4.nature();
        place4.area();
        place4.distance();
        place4.location();
        System.out.println("*************************-*-*-*-*-*-***********");
        Place place5 = new Bejjavalli();
        place5.location();
        place5.area();
        place5.nature();
        place5.distance();
        place5.nearPlace();
        System.out.println("////////////////////////////////////////////////");
        Place place6 = new Konandur();
        place6.nearPlace();
        place6.area();
        place6.location();
        place6.distance();
        place6.nearPlace();
        System.out.println("||||||||||||||||||||||||||||||||||||||||||||||||||");
        Place place7 = new Araga();
        place7.nearPlace();
        place7.area();
        place7.distance();
        place7.nature();
        place7.nearPlace();
        System.out.println(":::::::::::::::::::::::::::::::::::::::::::::::::::::");
        Place place8 = new Bettamakki();
        place8.nearPlace();
        place8.area();
        place8.nature();
        place8.distance();
        place8.location();
        System.out.println("........................................................");
        Place place9 = new Meenugoadu();
        place9.location();
        place9.nearPlace();
        place9.distance();
        place9.area();
        place9.nature();
        System.out.println("{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}");
        Orange orange = new Colour();
        orange.more();
        orange.no();
        orange.simple();
        orange.dark();
        orange.light();
        System.out.println("[][][][][][][][][][][][][][][][][][][][][][][][]");
        Food food1 = new Biriyani();
        food1.items();
        food1.name();
        food1.price();
        food1.type();
        food1.teast();
        System.out.println("||||||||\\\\\\\\\\\\\\\\\\\\\\\\||||||||");
        Food food2= new kadubu();
        food2.items();
        food2.name();
        food2.price();
        food2.type();
        food2.teast();
        System.out.println("()()()()()()()()()()()()()()()()()()()");
        Food food3 = new Puri();
        food3.items();
        food3.name();
        food3.type();
        food3.price();
        food3.teast();
        System.out.println("<><><><><><><><><><><><><><><><><><><>");
        Food food4 = new LemanRice();
        food4.items();
        food4.price();
        food4.name();
        food4.type();
        food4.teast();
        System.out.println(",.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.");
        Food food5 = new Meals();
        food5.items();
        food5.type();
        food5.name();
        food5.teast();
        food5.price();
        System.out.println("<<<<<<<<<<<>>>>>>>>>>>>><<<<<<<<<<<<>>>>>>>>>>>>");
        Food food6 = new Pizza();
        food6.items();
        food6.price();
        food6.name();
        food6.type();
        food6.teast();
        System.out.println(">>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>><<<<<<<<<<<");
        Food food7 = new Bargar();
        food7.items();
        food7.type();
        food7.price();
        food7.teast();
        food7.name();
        System.out.println("////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\");
        Food food8 = new plainDosa();
        food8.name();
        food8.type();
        food8.teast();
        food8.price();
        food8.items();
        System.out.println("[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]][[[[[[[[[[]]]]]]]]]");
        Food food9 = new Roti();
        food9.items();
        food9.type();
        food9.price();
        food9.teast();
        food9.name();
        System.out.println("0000000000000000000000000000000000000000000000000000000000000000");
        Food food10 = new Kabadu();
        food10.name();
        food10.teast();
        food10.price();
        food10.type();
        food10.items();
        System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<");
        Food food11 = new Chapathi();
        food11.items();
        food11.type();
        food11.name();
        food11.price();
        food11.teast();
        System.out.println("!@#$%^&*())(*&^%$#@!)");
        Food food12 = new Panipuri();
        food12.teast();
        food12.price();
        food12.name();
        food12.type();
        food12.items();
        System.out.println("}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{");
        Food food13 = new Dall();
        food13.items();
        food3.type();
        food13.name();
        food13.teast();
        food13.price();
        System.out.println("__________________________________________");
        Food food14 = new Coffe();
        food14.price();
        food14.teast();
        food14.type();
        food14.items();
        food14.name();
        System.out.println("Bondaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        Food food15 = new Bonda();
        food15.name();
        food15.type();
        food15.items();
        food15.price();
        food15.teast();
        System.out.println("<><><><><><><><><><><><><><><><><><><><>");
        Bank bank1 = new SBI();
        bank1.branch();
        bank1.email();
        bank1.name();
        bank1.managerName();
        bank1.code();
        System.out.println("'''''''''''''''''''''''''''''''''''''''''''''");
        Bank bank10 = new Bank();
        bank10.branch();
        bank10.email();
        bank10.name();
        bank10.managerName();
        bank10.code();
        System.out.println(",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,");
        Bank bank2 = new Canara();
        bank2.branch();
        bank2.email();
        bank2.name();
        bank2.managerName();
        bank2.code();
        System.out.println(":;;;;;;;;;;;;:::::::::::::::::::::::::::::::::::::::");
        Bank bank21 = new Bank();
        bank21.branch();
        bank21.email();
        bank21.name();
        bank21.managerName();
        bank21.code();
        System.out.println("................................................");
        Bank bank3 = new Union();
        bank3.branch();
        bank3.email();
        bank3.name();
        bank3.managerName();
        bank3.code();
        System.out.println("[][][][][][][][][][][][][][][][][][][][][]");
        Bank bank31 = new Bank();
        bank31.branch();
        bank31.email();
        bank31.name();
        bank31.managerName();
        bank31.code();
        System.out.println("//////////////////////////////////////////////////////");
        Bank bank4 = new ICIC();
        bank4.branch();
        bank4.email();
        bank4.name();
        bank4.managerName();
        bank4.code();
        System.out.println("[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]");
        Bank bank41 = new Bank();
        bank41.branch();
        bank41.email();
        bank41.name();
        bank41.managerName();
        bank41.code();
        System.out.println("{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}");
        Bank bank5 = new DCC();
        bank5.branch();
        bank5.email();
        bank5.name();
        bank5.managerName();
        bank5.code();
        System.out.println("()()()()()()()()()()()()()()()()()()()()()()");
        Bank bank6 = new Bank();
        bank6.branch();
        bank6.email();
        bank6.name();
        bank6.managerName();
        bank6.code();
        System.out.println("<><><><><><><><><><><?><><><><><><><><>");
        Bank bank7 = new Karnataka();
        bank7.branch();
        bank7.email();
        bank7.name();
        bank7.managerName();
        bank7.code();
        System.out.println("...............................................");
        Bank bank70 = new Bank();
        bank70.branch();
        bank70.email();
        bank70.name();
        bank70.managerName();
        bank70.code();
        System.out.println("{}{}{}{}{}{}{}{}{][][[][][][][]}{}{}{}{}{}");
        Bank bank8 = new Kodachadri();
        bank8.branch();
        bank8.email();
        bank8.name();
        bank8.managerName();
        bank8.code();
        System.out.println(":::::::::::::::::::::::::::::::::::::::::::::::::::::::::");
        Bank bank80 = new Bank();
        bank80.branch();
        bank80.email();
        bank80.name();
        bank80.managerName();
        bank80.code();
        System.out.println(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;");
        Bank bank9 = new ATM();
        bank9.branch();
        bank9.email();
        bank9.name();
        bank9.managerName();
        bank9.code();
        System.out.println(":::::::::::::::::::::::::::::::::::::::::::::::::::::");
        Bank bank90 = new Bank();
        bank90.branch();
        bank90.email();
        bank90.name();
        bank90.managerName();
        bank90.code();
        System.out.println("'''''''''''''''''''''''''''''''''''''");
        System.out.println("Instance Of Movie");
        System.out.println("");
        Movie movie = new Appu();
        movie.movieLocation();
        movie.movieName();
        movie.heroinName();
        movie.heroName();
        movie.rating();
        System.out.println("");
        Movie movie11 = new Movie();
        movie11.heroinName();
        movie11.heroName();
        movie11.movieLocation();
        movie11.rating();
        movie11.movieName();

        System.out.println("[][][][][][][[][][][][][][][][][][][][][][][][]");
        Movie movie1 = new Dragan();
        movie1.rating();
        movie1.movieName();
        movie1.movieLocation();
        movie1.heroName();
        movie1.heroinName();
        Movie movie21 = new Movie();
        movie21.heroName();
        movie21.movieName();
        movie21.movieLocation();
        movie21.movieName();
        movie21.rating();
        System.out.println("<><><><><><><><><><><><><><><><><><><>");
        System.out.println("Movie Max");
        System.out.println("");
        Movie movie2 = new Max();
        movie2.heroinName();
        movie2.movieLocation();
        movie2.heroName();
        movie2.rating();
        movie2.movieName();
        System.out.println("");
        Movie movie31 = new Movie();
        movie31.heroinName();
        movie31.heroName();
        movie31.movieName();
        movie31.movieLocation();
        movie31.rating();
        System.out.println("............................................");
        System.out.println("Movie Name Drama");
        System.out.println("................................................");
        Movie movie3 = new Drama();
        movie3.movieName();
        movie3.rating();
        movie3.heroName();
        movie3.movieLocation();
        movie3.heroinName();
        System.out.println("");
        Movie movie30 = new Movie();
        movie30.movieName();
        movie30.rating();
        movie30.heroName();
        movie30.movieLocation();
        movie30.heroinName();
        System.out.println("<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>");
        System.out.println("MOvie Name Mad");
        System.out.println("{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}");
        Movie movie4 = new Mad();
        movie4.heroinName();
        movie4.movieLocation();
        movie4.heroName();
        movie4.rating();
        movie4.movieName();
        System.out.println("");
        Movie movie40 = new Movie();
        movie40.heroinName();
        movie40.movieLocation();
        movie40.heroName();
        movie40.rating();
        movie40.movieName();
        System.out.println("......................................................");
        System.out.println("ABCD Movie");
        System.out.println(";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;");
        Movie movie5 = new ABCD();
        movie5.movieName();
        movie5.rating();
        movie5.movieLocation();
        movie5.heroName();
        movie5.heroinName();
        System.out.println("");
        Movie movie50 = new Movie();
        movie50.movieName();
        movie50.rating();
        movie50.movieLocation();
        movie50.heroName();
        movie50.heroinName();
        System.out.println("()()()()()()()()()()()()()()()()()()()()()()()()()()()()");
        System.out.println("Movie Kanthara Details");
        System.out.println("()()()()()()()()()()()()()()()()()()()()()()()()()()()()");
        Movie movie6 = new Kantara();
        movie6.heroinName();
        movie6.movieLocation();
        movie6.heroName();
        movie6.rating();
        movie6.movieName();
        System.out.println("?????????????????????????????????????????????????????????????");
        Movie movie60 = new Movie();
        movie60.heroinName();
        movie60.movieLocation();
        movie60.heroName();
        movie60.rating();
        movie60.movieName();
        System.out.println(".........................................................");
        System.out.println("Arasu Movie Details");
        System.out.println("..........................................................");
        Movie movie7 = new Arasu();
        movie7.movieName();
        movie7.rating();
        movie7.heroName();
        movie7.heroinName();
        movie7.movieLocation();
        System.out.println(",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,");
        Movie movie70 = new Movie();
        movie70.movieName();
        movie70.rating();
        movie70.heroName();
        movie70.heroinName();
        movie70.movieLocation();
        System.out.println("[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]");
        System.out.println("Abhi Movie Details");
        System.out.println(".............................................................. ");
        Movie movie8 = new Abhi();
        movie8.movieLocation();
        movie8.heroinName();
        movie8.rating();
        movie8.movieName();
        movie8.heroName();
        System.out.println("0000000000000000000000000000000000000000000000000000000000000000000000");
        Movie movie80 = new Movie();
        movie80.movieLocation();
        movie80.heroinName();
        movie80.rating();
        movie80.movieName();
        movie80.heroName();
        System.out.println("...............................................................");
        System.out.println("Movie Gaja Details");
        System.out.println("...............................................................");
        Movie movie9 = new Gaja();
        movie9.heroName();
        movie9.movieName();
        movie9.rating();
        movie9.heroinName();
        movie9.movieLocation();
        System.out.println("////////////////////////////////////////////////////////////////");
        Movie movie90 = new Movie();
        movie90.heroName();
        movie90.movieName();
        movie90.rating();
        movie90.heroinName();
        movie90.movieLocation();
        System.out.println("....................................................................");
        System.out.println("Dasa Movie Details");
        System.out.println("'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''");
        Movie movie10 = new Dasa();
        movie10.movieLocation();
        movie10.heroinName();
        movie10.movieName();
        movie10.heroName();
        movie10.rating();
        movie10.heroName();
        System.out.println("''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''");
        Movie movie100 = new Movie();
        movie100.movieLocation();
        movie100.heroinName();
        movie100.movieName();
        movie100.heroName();
        movie100.rating();
        movie100.heroName();
        System.out.println("IPL Teams Details");
        System.out.println("...........................................................................");
        System.out.println("Team RCB:)");
        System.out.println("............................................................................");
        IPL ipl1 = new RCB();
        ipl1.captanName();
        ipl1.loss();
        ipl1.win();
        ipl1.score();
        ipl1.color();
        System.out.println("................................................................................");
        IPL ipl11 = new IPL();
        ipl11.captanName();
        ipl11.loss();
        ipl11.win();
        ipl11.score();
        ipl11.color();
        System.out.println("................................................................................");
        System.out.println("Team CSK");
        System.out.println(".................................................................................");
        IPL ipl2 = new CSK();
        ipl2.color();
        ipl2.win();
        ipl2.score();
        ipl2.loss();
        ipl2.captanName();
        System.out.println("..............................................................................................");
        IPL ipl21 = new IPL();
        ipl21.color();
        ipl21.win();
        ipl21.score();
        ipl21.loss();
        ipl21.captanName();
        System.out.println("...................................................................................................");
        System.out.println("Team MI");
        System.out.println(".....................................................................................................");
        IPL ipl3 = new MI();
        ipl3.captanName();
        ipl3.loss();
        ipl3.win();
        ipl3.color();
        ipl3.score();
        System.out.println("........................................................................................................");
        IPL ipl30 = new IPL();
        ipl30.captanName();
        ipl30.loss();
        ipl30.win();
        ipl30.color();
        ipl30.score();
        System.out.println(".................................................");
        System.out.println("Team GT");
        System.out.println(".........................................................................................................");
        IPL ipl4 = new GT();
        ipl4.score();
        ipl4.color();
        ipl4.loss();
        ipl4.captanName();
        ipl4.win();
        System.out.println("...................................................");
        IPL ipl40 = new IPL();
        ipl40.score();
        ipl40.color();
        ipl40.loss();
        ipl40.captanName();
        ipl40.win();
        System.out.println(".................................................................................");
        System.out.println("Team KKR");
        System.out.println("............................................................................................");
        IPL ipl5 = new KKR();
        ipl5.loss();
        ipl5.color();
        ipl5.win();
        ipl5.captanName();
        ipl5.score();
        System.out.println("...............................................");
        IPL ipl50 = new IPL();
        ipl50.loss();
        ipl50.color();
        ipl50.win();
        ipl50.captanName();
        ipl50.score();
        System.out.println("...................");
        System.out.println("Games List");
        System.out.println("..........................................");
        Game game = new Cricket();
        game.captionName();
        game.date();
        game.team();
        game.number();
        game.name();
        System.out.println(".......................");
        Game game10 = new Game();
        game10.captionName();
        game10.date();
        game10.team();
        game10.number();
        game10.name();
        System.out.println("......................................");
        System.out.println("VallyBall Deatails");
        System.out.println("........................");
        Game game1 = new VallyBall();
        game1.name();
        game1.team();
        game1.number();
        game1.captionName();
        game1.date();
        System.out.println("......................................................");
        Game game11 = new Game();
        game11.name();
        game11.team();
        game11.number();
        game11.captionName();
        game11.date();

        System.out.println("....");
        System.out.println("Kabadi Game List");
        System.out.println("..................................");
        Game game2 = new Kabadi();
        game2.date();
        game2.number();
        game2.captionName();
        game2.team();
        game2.name();
        System.out.println("...........");
        Game game13 = new Game();
        game13.name();
        game13.team();
        game13.number();
        game13.captionName();
        game13.date();
        System.out.println(".................................");
        System.out.println("FootBall Game List");
        System.out.println("................................");
        Game game3 = new FootBall();
        game3.date();
        game3.number();
        game3.captionName();
        game3.team();
        game3.name();
        System.out.println(".........................................................");
        Game game31 = new Game();
        game31.date();
        game31.number();
        game31.captionName();
        game31.team();
        game31.name();
        System.out.println("....");
        System.out.println("Trow Ball Game List");
        System.out.println("..");
        Game game4 = new TrowBall();
        game4.date();
        game4.number();
        game4.captionName();
        game4.team();
        game4.name();
        System.out.println("");
        Game game41 = new Game();
        game41.date();
        game41.number();
        game41.captionName();
        game41.team();
        game41.name();
        System.out.println("");
        System.out.println("<><><><><><><>Students Details<><><><><><>");
        System.out.println("");
        System.out.println("Arun Student Details");
        Student student = new Arun();
        student.studentName();
        student.USN();
        student.branch();
        student.college();
        student.year();
        System.out.println(".....................");
        Student student20 = new Student();
        student20.studentName();
        student20.USN();
        student20.branch();
        student20.college();
        student20.year();
        System.out.println("......");
        System.out.println("Arjun Student Details");
        Student student1 = new Student();
        student1.studentName();
        student1.USN();
        student1.branch();
        student1.college();
        student1.year();
        System.out.println("");
        Student student21 = new Student();
        student21.studentName();
        student21.USN();
        student21.branch();
        student21.college();
        student21.year();

        System.out.println("");
        System.out.println("Azeem Student Details");
        Student student2 = new Student();
        student2.studentName();
        student2.USN();
        student2.branch();
        student2.college();
        student2.year();
        System.out.println("");
        Azeem azeem = new Azeem();
        azeem.branch();
        azeem.college();
        azeem.USN();
        azeem.studentName();
        azeem.year();
        System.out.println("..");
        System.out.println("Bharath Student Details");
        Student student4 = new Student();
        student4.studentName();
        student4.USN();
        student4.branch();
        student4.college();
        student4.year();
        System.out.println("..");
        Student bharath = new Bharath();
        bharath.branch();
        bharath.college();
        bharath.USN();
        bharath.studentName();
        bharath.year();
        System.out.println(".");
        System.out.println("Skanda Student Details");
        Student student5 = new Student();
        student5.studentName();
        student5.USN();
        student5.branch();
        student5.college();
        student5.year();
        System.out.println(".................");
        Student skanda = new Skanda();
        skanda.branch();
        skanda.college();
        skanda.USN();
        skanda.studentName();
        skanda.year();
        System.out.println("");
        System.out.println("Sagar D Student Details");
        Student student6 = new Student();
        student6.studentName();
        student6.USN();
        student6.branch();
        student6.college();
        student6.year();
        System.out.println("..........................................................................................................................................................");
        Student sagar = new Sagar();
        sagar.branch();
        sagar.college();
        sagar.USN();
        sagar.studentName();
        sagar.year();
        System.out.println("....");
        System.out.println("Shriharsha Student Details");
        Student student7 = new Student();
        student7.studentName();
        student7.USN();
        student7.branch();
        student7.college();
        student7.year();
        System.out.println("");
        Student shriharsha = new Shriharsha();
        shriharsha.branch();
        shriharsha.college();
        shriharsha.USN();
        shriharsha.studentName();
        shriharsha.year();
        System.out.println("..................................");
        System.out.println("Farhan Kahan Student Details");
        Student student8 = new Student();
        student8.studentName();
        student8.USN();
        student8.branch();
        student8.college();
        student8.year();
        System.out.println("..............................................");
        Student faran = new Faran();
        faran.branch();
        faran.college();
        faran.USN();
        faran.studentName();
        faran.year();
        System.out.println("");
        System.out.println("Pravith A P Student Details");
        Student student9 = new Student();
        student9.studentName();
        student9.USN();
        student9.branch();
        student9.college();
        student9.year();
        System.out.println(".............................");
        Student pravith = new Pravith();
        pravith.branch();
        pravith.college();
        pravith.USN();
        pravith.studentName();
        pravith.year();
        System.out.println("................");
        System.out.println("Maruthi Prasanna C N Student Details");
        Student student10 = new Student();
        student10.studentName();
        student10.USN();
        student10.branch();
        student10.college();
        student10.year();
        System.out.println("");
        Student maruthi = new Maruthi();
        maruthi.branch();
        maruthi.college();
        maruthi.USN();
        maruthi.studentName();
        maruthi.year();

        System.out.println("........");
        System.out.println("Pratham Francis Student Details");
        Student student11 = new Student();
        student11.studentName();
        student11.USN();
        student11.branch();
        student11.college();
        student11.year();
        System.out.println("......................................");
        Student pratham= new Pratham();
        pratham.branch();
        pratham.college();
        pratham.USN();
        pratham.studentName();
        pratham.year();

        System.out.println(".....");
        System.out.println("Preetham B Student Details");
        Student student12 = new Student();
        student12.studentName();
        student12.USN();
        student12.branch();
        student12.college();
        student12.year();
        System.out.println("....");
        Student preetham = new Preetham();
        preetham.branch();
        preetham.college();
        preetham.USN();
        preetham.studentName();
        preetham.year();
        System.out.println("...");
        System.out.println("Dhanush M P Student Details");
        Student student13 = new Student();
        student13.studentName();
        student13.USN();
        student13.branch();
        student13.college();
        student13.year();
        System.out.println("..................................");
        Student dhanush = new Dhanush();
        dhanush.branch();
        dhanush.college();
        dhanush.USN();
        dhanush.studentName();
        dhanush.year();
        System.out.println("............................");
        System.out.println("Pavan L Student Details");
        Student student14 = new Student();
        student14.studentName();
        student14.USN();
        student14.branch();
        student14.college();
        student14.year();
        System.out.println("...........");
        Student pavan = new Pavan();
        pavan.branch();
        pavan.college();
        pavan.USN();
        pavan.studentName();
        pavan.year();
        System.out.println(".....");
        System.out.println("Kowstubha Hegade M A Student Details");
        Student student15 = new Student();
        student15.studentName();
        student15.USN();
        student15.branch();
        student15.college();
        student15.year();
        System.out.println(".");
        Student kowstubha = new Kowstubha();
        kowstubha.branch();
        kowstubha.college();
        kowstubha.USN();
        kowstubha.studentName();
        kowstubha.year();
        System.out.println("........................................................................................................");
        System.out.println("Srujan Student Details");
        Student student16 = new Student();
        student16.studentName();
        student16.USN();
        student16.branch();
        student16.college();
        student16.year();
        System.out.println("");
        Student srujan = new Srujan();
        srujan.branch();
        srujan.college();
        srujan.USN();
        srujan.studentName();
        srujan.year();
        System.out.println("..................................................................................................................................");
        System.out.println("Thapaswi Student Details");
        Student student17 = new Student();
        student17.studentName();
        student17.USN();
        student17.branch();
        student17.college();
        student17.year();
        System.out.println("..............................................................................................................");
        Student thapaswi = new Thapaswi();
        thapaswi.branch();
        thapaswi.college();
        thapaswi.USN();
        thapaswi.studentName();
        thapaswi.year();
        System.out.println(".............................................................................................................................");
        System.out.println("Charan D Student Details");
        Student student18 = new Student();
        student18.studentName();
        student18.USN();
        student18.branch();
        student18.college();
        student18.year();
        System.out.println("");
        Student charan = new Charan();
        charan.branch();
        charan.college();
        charan.USN();
        charan.studentName();
        charan.year();

        System.out.println("");
        System.out.println("Adhya K S Student Details");
        Student student19 = new Student();
        student19.studentName();
        student19.USN();
        student19.branch();
        student19.college();
        student19.year();
        System.out.println("");
        Student adhya = new Adhya();
        adhya.branch();
        adhya.college();
        adhya.USN();
        adhya.studentName();
        adhya.year();


    }

}
